server:
  port: 8089

#是否开启 swagger-ui
swagger:
  enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3000MB
      max-request-size: 3000MB

# 文件存储路径
file:
  mac:
    path: ~/file/
    rootPath: ~/file/audio_root/ #压缩包解压缩文件夹
  linux:
    path: /home/aias/file/
    rootPath: /home/aias/file/audio_root/ #压缩包解压缩文件夹
  windows:
    path: file:///D:/aias/file/
    rootPath: file:///D:/aias/file/audio_root/ #压缩包解压缩文件夹
  # 文件大小 /M
  maxSize: 3000

# Voice 
audio:
  # 特征提取模型
  feature: https://aias-home.oss-cn-beijing.aliyuncs.com/models/speech_models/voiceprint.zip
  #  path: /Users/calvin/Documents/audio_root/ #文件存放文件夹
  baseUrl: http://127.0.0.1:8089/files/
  
# 向量引擎 Milvus
search:
  host: 127.0.0.1
  port: 19530
  indexFileSize: 1024 # maximum size (in MB) of each index file
  nprobe: 256
  nlist: 16384
  dimension: 512 # dimension of each vector
  collectionName: voiceprint #collection name